### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by carterkelly9** [jacahill/hPSMC#4]
The README needs a couple tweaks for spelling/grammar issues (PR coming ASAP)!

**Comment by jacahill** [comment]
Care to elaborate?  What is PR?

**Comment by carterkelly9** [comment]
PR is a pull request, the link is here: https://github.com/jacahill/hPSMC/pull/3
If accepted, the changes I made to your README will be merged to your master branch.

**Comment by jacahill** [comment]
I see thanks for the notes. I've approved the changes.

Thanks
